### ISSUE TITLE
Several questions about the training

### ISSUE THREAD

**Issue by mrgreen3325** [ARM-software/sesr#11]
Thanks for your work.
I got several questions about the training and the tflite generation.
1. I notice the tflite is using  converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(saved_model). Is that the tflite model is for tf 1.x version?
2. If gen_tflite = true, the model will use relu and batch to space instead of prelu and depth to space, may I know the reason?
3. If I use --linear_block_type expanded for training, how can I collapse the model after training?
4. how can I random crop the hr-lr at each epoch instead of the pre-randomcrop the hr-lr before the training?
Thanks a lot.

**Comment by kbhardwa** [comment]
Hi. Sorry for the delay. Here are the answers:

1. The tflite is generated using tensorflow version 2.3 so the tflite works for tf2.x version. 
2. The prelu was replaced with relu for quantized model because it leads to some more efficiency (prelu adds some more MACs compared to relu). The transpose->batch-to-space->transpose is exactly equivalent to depth-to-space so it does not matter. We used some of these things simply because earlier we were using an older version of tensorflow and depth-to-space was not supported back then in tflite. This is why we still have some tf.compat.v1 statements in the code when it comes to tflite. We may update the code later but it is not currently planned. 
3. The collapsing procedure is similar to that given [here](https://github.com/ARM-software/sesr/blob/26dd727996809fe13efb0c0f137f259c1b2d0f6e/models/model_utils.py#L190-L200). One of the main changes will be that you will need to retrieve trained weights from the saved model and then use those trained weights in [convolutions at line 190 in model_utils.py (i.e., convs inside self.collapse)](https://github.com/ARM-software/sesr/blob/26dd727996809fe13efb0c0f137f259c1b2d0f6e/models/model_utils.py#L190). We recommend to use the collapsed_linear_block mode since we have provided quantization support for SESR for collapsed_linear_block.
4. HR-LR are cropping randomly at each training step already. The code [here](https://github.com/ARM-software/sesr/blob/26dd727996809fe13efb0c0f137f259c1b2d0f6e/train.py#L67-L74) takes care of all the data augmentation.
