### ISSUE TITLE
PSNR calculation on Y-Channel

### ISSUE THREAD

**Issue by eternalding** [ARM-software/sesr#5]
Greetings.
As the entire model is converted from RGB to Y-Channel before training, the pixel value should range from 16~235.
If so, why is the y channel divided by 255, and is it proper to calculate PSNR with max_val = 1.0?
Look forward to your reply.

Sincerely,
Wenny

**Comment by kbhardwa** [comment]
Hi Wenny, the 255 is normally chosen because it is the limit of the data type (in our case for images, the data type is uint8, so the MAX value is 255). Please see [here](https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio). This is a standard practice in SR. For instance, please see official codes of other papers as well. Example, ECCV 2020 paper: Tiny Perceptual SR (TPSR) code also uses 255 (along with many others). See [here](https://github.com/royson/tpsr/blob/76440813e988d02b1274907139b3319d4c3d2008/utils.py#L48).

This is why for our case, we have divided by 255 and then used max_val=1.0. We have also verified that this results in exactly the same PSNR for other baselines like bicubic, etc., for which PSNR numbers have been reported in all SR papers.
