### ISSUE TITLE
 how to simulate hardware performance 

### ISSUE THREAD

**Issue by SJHNJU** [ARM-software/sesr#9]
Nice  Work and a great contribution for hardware-friendly SR!

May I ask how to simulate AI model performance for Arm Ethos-N78 NPU? Is there any reference or website？ I cannot find the simulation platform on the  Arm official website. 

Thank you !!

**Comment by mrgreen3325** [comment]
> Nice Work and a great contribution for hardware-friendly SR!
> 
> May I ask how to simulate AI model performance for Arm Ethos-N78 NPU? Is there any reference or website？ I cannot find the simulation platform on the Arm official website.
> 
> Thank you !!

Hello. May I know do you run the training succesfully?
When I run the train.py, I get the error.
`runtimeerror: abortederror: failed to construct dataset div2k/bicubic_x4: all 10 retry attempts failed.`
It seems to be the dataset problem, do you meet this problem?
Thanks.

**Comment by wyfzka** [comment]
> Nice Work and a great contribution for hardware-friendly SR!
> 
> May I ask how to simulate AI model performance for Arm Ethos-N78 NPU? Is there any reference or website？ I cannot find the simulation platform on the Arm official website.
> 
> Thank you !!

I meet some questions when I run the train.py.
 it seems that failed to create cublas handel: CUBLAS_STATUS_NOT_INITIALIZED.
have you met this problem? Thanks

**Comment by kbhardwa** [comment]
Hi all, sorry for the delay. We were working to release the new version of the paper which is now released on arXiv.

Thanks @SJHNJU. Please see section 5.8 in the new version. It contains more details on performance estimation for another Arm NPU: Ethos-U55 micro-NPU. The performance estimator for Ethos-U55 is open source and you only need to input a tflite. More details in the paper.

@wyfzka This sounds like either a tensorflow installation issue or maybe something related to GPU out-of-memory issue. Please try reducing the batch size and see if this still happens. Otherwise, please check your tensorflow installation.

@mrgreen3325 Are you still facing issues? I am unable to reproduce your error. Please make sure your tensorflow datasets is version 4.1 or later.
